# Generated by Django 2.2.12 on 2020-06-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0003_ordered_releases'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('series', 'slug'), ('order_index', 'series')},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('order_index', 'release')},
        ),
    ]
